### PR TITLE
xbox: Fix incorrect behavior of log, exp and pow functions

### LINKED ISSUE #25: `pow()` leads to issues in SDL2 audio conversion
See https://github.com/XboxDev/nxdk-sdl/pull/20#issuecomment-581448832

Additionally, I noticed that the math functions don't have any copyright header or note where they stem from / wether they were tested; this makes it hard to analyze / report such issues.

It is worth noting that the code for different precisions is exactly the same (except for type suffix on `float` constants). I'm not sure if this is enough / correct.

I also believe we never set up or check the control words for precision (I expected this in crt0). So it might be possible to get different results on different runs, depending on how the XBE was started?

### PR DESCRIPTION
**Pull request by thrimbor**
This fixes the issues in SDL's sampling rate conversion caused by our math functions. `log` and `exp` incorrectly handled special values (`INFINITY`, `-INFINITY`, `NAN` and `-NAN`). `log` was fixed by slightly tweaking the algorithm, while `exp` does check for special values before calculating (this approach seems to be common, I've seen it in Sortix's libm, too).

The problem in `pow`, and this is the main reason why SDL would hang, was that it would return `NAN` for negative bases (the logarithm of a negative number is a complex number). This was fixed by simply using the absolute value of the base. I also added glibc's behavior of returning `-NAN` when the function is called with a negative base and a non-integer exponent.

The behavior of all functions modified here was checked against glibc using positive, negative and special values. I have some test code [here](https://gist.github.com/thrimbor/c1f4b18ecd8be001f414f5a25d72716b) to verify that the SDL issue is solved (remember to enable `HAVE_POW` in `SDL_config_xbox.h` - the sample should hang without the changes and work with them).

Closes #25.

### CODE REVIEW

File: platform/xbox/functions/math/pow.c [hunk 1]
```diff
@@ -2,15 +2,24 @@
 
 double pow(double x, double y)
 {
-    return exp(y*log(x));
+    if (x < 0.0 && y != trunc(y)) {
+        return -NAN;
+    }
+    return exp(y*log(fabs(x)));
```
Comment (JayFoxRox) [inline platform/xbox/functions/math/pow.c]: Taking the absolute of `x` looks wrong.
I did not confirm against the C spec or another libc, but I'd assume that:

- `(-1) ^ 1` should be `-1`
- `(-1) ^ 2` should be `+1`
- `(-1) ^ 3` should be `-1`
- ...

but your implementation would be using:

- `abs(-1) ^ 1` will be `+1` (this would be incorrect)
- `abs(-1) ^ 2` will be `+1`
- `abs(-1) ^ 3` will be `+1` (this would be incorrect)
- ...

Comment (thrimbor) [reply platform/xbox/functions/math/pow.c]: Oops. I didn't test the combination of a negative base with an odd exponent. I now pushed implementations for `copysign` and `remainder` and used them to fix this case.

File: platform/xbox/functions/math/pow.c [hunk 2]
```diff
@@ -2,15 +2,48 @@
...
-    return expf(y*logf(x));
+    if (x < 0.0f && y != truncf(y)) {
+        // Negative base and non-integer exponent
+        return -NAN;
+    }
+
+    float r = expf(y * logf(fabsf(x)));
+
+    if (x < 0.0f && remainderf(y, 2.0f) != 0) {
+        r = copysignf(r, x);
```
Comment (JayFoxRox) [inline platform/xbox/functions/math/pow.c]: `copysign` shouldn't be necessary, because we already made sure that `x` is negative.
So `r = -r` should always be the same, but potentially faster.

Or was this done to handle NaN or Inf or something in a special way?

File: platform/xbox/functions/math/pow.c [hunk 3]
```diff
@@ -2,15 +2,48 @@
...
 {
-    return expf(y*logf(x));
+    if (x < 0.0f && y != truncf(y)) {
+        // Negative base and non-integer exponent
+        return -NAN;
+    }
+
+    float r = expf(y * logf(fabsf(x)));
+
+    if (x < 0.0f && remainderf(y, 2.0f) != 0) {
```
Comment (JayFoxRox) [inline platform/xbox/functions/math/pow.c:28]: I'm not sure if `remainderf` is a good idea. I worry that it's potentially slow.
It appears to do an internal loop or division, so `fprem1` seems to be one of the slowest x87 instructions.

While this should rarely affect us (because most of the time `x > 0.0`), I wonder how other implementations handle it.

File: platform/xbox/functions/math/pow.c (hunk 2 above)
Comment (thrimbor) [reply platform/xbox/functions/math/pow.c]: Ah, this should indeed be simplified. Done.

File: platform/xbox/functions/math/pow.c (hunk 3 above)
Comment (thrimbor) [reply platform/xbox/functions/math/pow.c:28]: Most code I have seen is derived from [Sun's implementation](https://gitlab.com/sortix/sortix/-/blob/master/libm/src/e_pow.c), which involves tons of non-trivial C code. I'm pretty sure it's more accurate, but it's crazy complex (and comes with a custom license note).

I'm open to improving this function in the future, but I'm not too worried about it being too slow rn.

**Review by dracc — APPROVED** [review]
Reading through the code changes, they're obviously better than master. I'm not overly familiar with ieee754 though.
Looks good to me.
